### ISSUE TITLE
Question - committing message manually

### ISSUE THREAD

**Issue by yaman** [CallistoLabsNYC/samsa#100]
Hi there, great library! Thanks a lot for the effort. I would like to know if I can commit message when I am only done with it. Consider this example;

```rust
while let Some(message) = stream.next().await {
   let messages: Vec<ConsumeMessage> = message.unwrap().collect();
  
   do_some_operation(messages);

   // commit message here wit stream.commit or something else?
   // stream.commit(message);
   
}
```

I don't know if I truly understand the lifecycle of the message here though. I would need this behavior especially when processing messages asynchronously on a different thread.

thanks in advance.

**Comment by hgm-king** [comment]
Hiya, thanks for checking this out! This is something we support:

I have made an autocommit stream so that this exact logic you shared occurs. If you look at [this function](https://github.com/CallistoLabsNYC/samsa/blob/main/src/consumer.rs#L305) then you can see that it will yield a set of messages (batches are always used) and then commit after it is used, i.e. when the next set is fetched.

This means that each time you do `stream.next()`, it assumes you are done with the previous batch and commits it as 'consumed'.

Furthermore, if that doesn't suite your use case exactly:

You could build your own consumer with commit by using the lower level functions, in a similar manner to how we do in the link I shared above. The logic isn't so hard as long as you understand how to make streams

**Comment by yaman** [comment]
Thanks a lot! I will take a look at it closer.
